debug: false
uuid: ""
token_id: ""
token: ""
api:
  host: "0.0.0.0"
  port: 8080
  ssl:
    enabled: false
  upload_limit: 100
system:
  log_directory: /var/log/pterodactyl
  data: /var/lib/pterodactyl/volumes
  archive_directory: /var/lib/pterodactyl/backups
  user:
    uid: 988
    gid: 988
allowed_mounts: []
allowed_origins:
  - "*"
